music_directory    "/home/unemotioned/Music/"
playlist_directory "/home/unemotioned/Music/Playlists/"
db_file            "/home/unemotioned/.local/share/mpd/database"

auto_update     "yes"
bind_to_address "127.0.0.1"
restore_paused  "yes"

audio_output {
    type "pipewire"
    name "PipeWire"
}
